checks:
  example:
    max: 10
    enabled: true
  motion:
    gravity:
      max: 15
      enabled: true
    jump:
      max: 15
      enabled: true
  speed:
    friction:
        max: 10
        enabled: true

