alert-permission: sequence.alerts

checks:
#MOVMEMENT
  motion:
    gravity:
      max: 15
      enabled: true
    jump:
      max: 15
      enabled: true
  speed:
    horizontal:
      max: 10
      enabled: true
  flight:
    stable:
      max: 5
      enabled: true
    airjump:
      max: 10
      enabled: true
  step:
    height:
      max: 10
      enabled: true
#COMBAT
  aim:
    sigma:
      max: 10
      enabled: true
    basicgcd:
      max: 5
      enabled: true
    sensivitygcd:
      max: 25
      enabled: true
  aura:
    post:
      max: 25
      enabled: true
    swing:
      max: 5
      enabled: true
#OTHERS
  invalidpackets:
    mathground:
      max: 25
      enabled: true
    abilitiesflying:
      max: 3
      enabled: true



