checks:
  example:
    max: 10
    enabled: true
  motion:
    gravity:
      max: 15
      enabled: true
    jump:
      max: 15
      enabled: true
  speed:
    horizontal:
      max: 10
      enabled: true
  flight:
    stable:
      max: 5
      enabled: true
    airjump:
      max: 10
      enabled: true
  aim:
    sigma:
      max: 10
      enabled: true
    basicgcd:
      max: 5
      enabled: true


