color:
  main: '&c'
  secondary: '&f'

# These are all placeholders that can be used in alert format and alert hover info
# %player%, %check%, %subname%, %experimental%, %vl%, %info%, %description%, %keepaliveping%,
# %transping%, %lagging%, %version%, %tps%, %client%, %max%
alerts:
  format: '&8[&cSequence&8] &c%player% &7failed &c%check% &8(&f%subname%&8) &8(&cx%vl%&8)'
  # In seconds
  delay: 0.5
  on-join: true
  hover-info:
    - '&cInfo: &f%info%'
    - ' '
    - '&cTPS: &f%tps%'
    - '&cPing: &f%keepaliveping%'
    - '&cLagging: &f%lagging%'
    - '&cClient: &f%client%'
    - ' '
    - '&eClick to TP!'
  # Only %player% works on click-command
  click-command: '/tp %player%'
  permission: 'sequence.alerts'
